
package net.exchangenetwork.wsdl.node._2;

import javax.xml.ws.WebFault;
import net.exchangenetwork.schema.node._2.NodeFaultDetailType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NodeFaultDetailType", targetNamespace = "http://www.exchangenetwork.net/schema/node/2")
public class NodeFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NodeFaultDetailType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public NodeFaultMessage(String message, NodeFaultDetailType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public NodeFaultMessage(String message, NodeFaultDetailType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: net.exchangenetwork.schema.node._2.NodeFaultDetailType
     */
    public NodeFaultDetailType getFaultInfo() {
        return faultInfo;
    }

}
